services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.23.0
    restart: unless-stopped

    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "--credentials-file=/secrets/gcloud/application_default_credentials.json"
      - "${CLOUD_SQL_INSTANCE}"

    volumes:
      - "${GOOGLE_APPLICATION_CREDENTIALS_HOST}:/secrets/gcloud/application_default_credentials.json:ro"

  api:
    build: .
    restart: unless-stopped

    depends_on:
      - cloud-sql-proxy

    environment:
      DB_HOST: cloud-sql-proxy
      DB_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}

      POSTGRES_USER: ${USER_DEV}
      POSTGRES_PASSWORD: ${USER_DEV_PASSWORD}

      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}

      APP_PORT: 8080

    ports:
      - "${APP_PORT}:8080"
