name: CI/CD Backend Java+Maven

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

env:
  PROJECT_ID: reto-universitario-2026
  REGION: us-central1
  SERVICE: api-dev
  IMAGE: us-central1-docker.pkg.dev/reto-universitario-2026/backend-dev/api

jobs:
  # -- CI
  unit-test-backend:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Give execute permission to mvnw
        run: chmod +x mvnw
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw test

  docker-build-check-backend:
    name: Check dockerfile builds
    needs: unit-test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t temp-image:ci-check .
  
  # -- CD (Desactivado hasta que se pueda autenticar el github-deployer con GCP)
  
#  build-and-deploy:
#   name: Build, push y deploy a Cloud Run
#   needs: [unit-test-backend, docker-build-check-backend]
#   if: github.event_name == 'push'
#   runs-on: ubuntu-latest
#   permissions:
#     contents: read
#      id-token: write

#   steps:
#     - uses: actions/checkout@v4

#     - name: Autenticar contra Google Cloud
#       uses: google-github-actions/auth@v2
#       with:
#         workload_identity_provider: 'projects/163845318284/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
#          service_account: 'github-deployer@reto-universitario-2026.iam.gserviceaccount.com'

#     - uses: google-github-actions/setup-gcloud@v2

#     - name: Configurar Docker para Artifact Registry
#       run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

#     - name: Build de la imagen
#       run: docker build -t ${{ env.IMAGE }}:${{ github.sha }} .

#     - name: Push a Artifact Registry
#       run: docker push ${{ env.IMAGE }}:${{ github.sha }}

#     - name: Deploy a Cloud Run
#       uses: google-github-actions/deploy-cloudrun@v2
#       with:
#         service: ${{ env.SERVICE }}
#         region: ${{ env.REGION }}
#         image: ${{ env.IMAGE }}:${{ github.sha }}
#         flags: '--min-instances=0 --max-instances=2 --cpu=1 --memory=512Mi --allow-unauthenticated'



